print("\nWelcome to the Program")
import math
print("\n")
print(int(3+4)*5)
print("\n")
n=int(input("Kindly enter the value of n : "))
print(n*(n-1)/2)
print("\n")
r=int(input("Kindly enter the value of r : "))
print(4*3.14*r**2)
print("\n")
a=int(input("Kindly enter the value of a : "))
b=int(input("Kindly enter the value of b : "))
print(((r*(math.cos(a)**2)) + (r*(math.sin(b)**2)))**0.5)
print("\n")
y2=int(input("Kindly enter the value of y2 : "))
y1=int(input("Kindly enter the value of y1 : "))
x2=int(input("Kindly enter the value of x1 : "))
x1=int(input("Kindly enter the value of x2 : "))
print((y2-y1)/(x2-x1) )